### PR TITLE
add script to remove local branched already merged to current branch

### PR DESCRIPTION
**Pull request by echoi92**

### CODE REVIEW

**Review by nickangtc — COMMENTED** [review]
@Maestro501 possible to add a description to help us understand what this does? I'm not sure what it's going to clean and when to use it ❓

**Comment by echoi92** [comment]
It will remove all local branches that are already merged to your current checked-out branch.

ex
```
(from master)
git checkout feature-branch
git add . && git commit -m "my feature"
git push origin feature-branch
// make PR in github
// accept PR in github
git checkout master // important!!
git pull origin master
bash clean-git.sh

// local feature-branch removed, cos it's alrady merged to master through PR in github
```

**Comment by Maestro501** [comment]
testing slack integration

**Comment by echoi92** [comment]
Oh you mean in the script file?

**Comment by nickangtc** [comment]
Oh I see what it does now that you've explained it. Very useful script! Yes I think it's best to make a note of what this does exactly, because the commands in the .sh script are not self evident

**Comment by echoi92** [comment]
Added one more line in comment.

**Review by nickangtc — APPROVED** [review]

**Pull request merged**
